/* eslint-disable @next/next/no-page-custom-font */
export default function Head() {
  return (
    <>
      <title>Pricing Ui Using Tailwind Css With Nextjs 13 by M.B</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
    </>
  )
}
